import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {unzipSync,strFromU8} from 'fflate';
import {build} from './build.mjs';
const base=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../work');
await fs.mkdir(base,{recursive:true});
const root=await fs.mkdtemp(path.join(base,'check-'));
const project=path.resolve(base,'..');
for(const file of ['index.html','style.css','app.js','site.config.json'])await fs.copyFile(path.join(project,file),path.join(root,file));
await fs.mkdir(path.join(root,'skills/中文 skill/scripts'),{recursive:true});
await fs.writeFile(path.join(root,'skills/中文 skill/SKILL.md'),'---\nname: 测试 Skill\ndescription: |\n  第一行\n  第二行\n---\n# 测试');
await fs.writeFile(path.join(root,'skills/中文 skill/scripts/run.txt'),'配套文件');
await fs.writeFile(path.join(root,'skills/中文 skill/.hidden'),'hidden');
const rows=await build(root);
assert.equal(rows[0].files,3);assert.equal(rows[0].name,'测试 Skill');assert.match(rows[0].description,/第二行/);
const zipped=unzipSync(await fs.readFile(path.join(root,'dist/downloads/中文 skill.zip')));
assert.equal(strFromU8(zipped['中文 skill/scripts/run.txt']),'配套文件');assert.equal(strFromU8(zipped['中文 skill/.hidden']),'hidden');
const context={window:{}};vm.runInNewContext(await fs.readFile(path.join(root,'dist/catalog.js'),'utf8'),context);assert.equal(context.window.SKILLS_CATALOG.skills.length,1);
await fs.rename(path.join(root,'skills/中文 skill'),path.join(root,'removed-skill'));
await build(root);assert.deepEqual(await fs.readdir(path.join(root,'dist/downloads')),[]);
console.log('PASS: YAML、中文路径、附件、隐藏文件、ZIP 内容、目录数据、删除同步');
