import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {zipSync,strToU8} from 'fflate';
import {build} from './build.mjs';
const root=await fs.mkdtemp(path.resolve('work/zip-check-'));
await fs.mkdir(path.join(root,'skills'));
for(const file of ['index.html','app.js','style.css','site.config.json'])await fs.copyFile(file,path.join(root,file));
const doc=strToU8('---\nname: ZIP 测试\ndescription: 完整附件\n---\n# Skill');
const a=zipSync({'SKILL.md':doc,'scripts/run.txt':strToU8('附件')});
const b=zipSync({'nested/SKILL.md':doc,'nested/templates/中文.txt':strToU8('模板')});
await fs.writeFile(path.join(root,'skills/直接.zip'),a);
await fs.writeFile(path.join(root,'skills/有文件夹.ZIP'),b);
let records=await build(root);assert.equal(records.length,2);assert.equal(records[0].name,'ZIP 测试');assert.equal(records[0].sourceType,'blob');
assert.deepEqual(await fs.readFile(path.join(root,'dist/downloads/直接.zip')),Buffer.from(a));
await fs.writeFile(path.join(root,'skills/bad.zip'),zipSync({'../SKILL.md':doc}));
await assert.rejects(build(root),/不安全路径/);
await fs.writeFile(path.join(root,'skills/bad.zip'),zipSync({'README.md':doc}));
await assert.rejects(build(root),/明确的 SKILL.md/);
await fs.writeFile(path.join(root,'skills/bad.zip'),zipSync({'a/SKILL.md':doc,'b/SKILL.md':doc}));
await assert.rejects(build(root),/明确的 SKILL.md/);
await fs.writeFile(path.join(root,'skills/bad.zip'),Buffer.from('not a zip'));
await assert.rejects(build(root));
console.log('PASS: root/nested ZIP, uppercase extension, Chinese paths, original archive bytes, invalid archives and traversal rejection');
